-- 	require("mason").setup()
--
--   {
-- 		"neovim/nvim-lspconfig", -- kept only for server default configs
-- 		dependencies = { "hrsh7th/cmp-nvim-lsp" },
-- 		config = function()
-- 			-- Keymaps: attach to every LSP buffer via the new autocmd API
-- 			vim.api.nvim_create_autocmd("LspAttach", {
-- 				group = vim.api.nvim_create_augroup("UserLspAttach", { clear = true }),
-- 				callback = function(ev)
-- 					local opts = { buffer = ev.buf }
-- 					vim.keymap.set(
-- 						"n",
-- 						"gd",
-- 						vim.lsp.buf.definition,
-- 						vim.tbl_extend("force", opts, { desc = "Go to Definition" })
-- 					)
-- 					vim.keymap.set(
-- 						"n",
-- 						"gr",
-- 						vim.lsp.buf.references,
-- 						vim.tbl_extend("force", opts, { desc = "Go to References" })
-- 					)
-- 					vim.keymap.set(
-- 						"n",
-- 						"gi",
-- 						vim.lsp.buf.implementation,
-- 						vim.tbl_extend("force", opts, { desc = "Go to Implementation" })
-- 					)
-- 					vim.keymap.set(
-- 						"n",
-- 						"K",
-- 						vim.lsp.buf.hover,
-- 						vim.tbl_extend("force", opts, { desc = "Hover Documentation" })
-- 					)
-- 					vim.keymap.set(
-- 						"n",
-- 						"<leader>rn",
-- 						vim.lsp.buf.rename,
-- 						vim.tbl_extend("force", opts, { desc = "Rename Symbol" })
-- 					)
-- 					vim.keymap.set(
-- 						"n",
-- 						"<leader>ca",
-- 						vim.lsp.buf.code_action,
-- 						vim.tbl_extend("force", opts, { desc = "Code Action" })
-- 					)
-- 				end,
-- 			})
--
-- 			local capabilities = require("cmp_nvim_lsp").default_capabilities()
--
-- 			-- Servers that need no special config
-- 			local servers = { "ts_ls", "angularls", "html", "cssls", "rust_analyzer" }
-- 			for _, server in ipairs(servers) do
-- 				vim.lsp.config(server, { capabilities = capabilities })
-- 			end
--
-- 			-- ESLint: disable formatting so conform.nvim stays in charge
-- 			vim.lsp.config("eslint", {
-- 				capabilities = capabilities,
-- 				on_attach = function(client, _)
-- 					client.server_capabilities.documentFormattingProvider = false
-- 					client.server_capabilities.documentRangeFormattingProvider = false
-- 				end,
-- 				settings = {
-- 					workingDirectories = { mode = "auto" },
-- 					experimental = { useFlatConfig = nil },
-- 				},
-- 			})
--
-- 			-- Lua: tell the server "vim" is a valid global
-- 			vim.lsp.config("lua_ls", {
-- 				settings = {
-- 					Lua = { diagnostics = { globals = { "vim" } } },
-- 				},
-- 			})
--
-- 			vim.lsp.enable({
-- 				"ts_ls",
-- 				"angularls",
-- 				"html",
-- 				"cssls",
-- 				"eslint",
-- 				"lua_ls",
-- 				"roslyn",
-- 				"rust_analyzer",
-- 			})
-- 		end,
-- 	},
-- }
